/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyTest"
 * 	found in "../MyTest.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_Counter32_H_
#define	_Counter32_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Counter32 */
typedef long	 Counter32_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Counter32;
asn_struct_free_f Counter32_free;
asn_struct_print_f Counter32_print;
asn_constr_check_f Counter32_constraint;
ber_type_decoder_f Counter32_decode_ber;
der_type_encoder_f Counter32_encode_der;
xer_type_decoder_f Counter32_decode_xer;
xer_type_encoder_f Counter32_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Counter32_H_ */
