/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyTest"
 * 	found in "../MyTest.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_Message_H_
#define	_Message_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Message */
typedef long	 Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Message;
asn_struct_free_f Message_free;
asn_struct_print_f Message_print;
asn_constr_check_f Message_constraint;
ber_type_decoder_f Message_decode_ber;
der_type_encoder_f Message_encode_der;
xer_type_decoder_f Message_decode_xer;
xer_type_encoder_f Message_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Message_H_ */
