/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyTest"
 * 	found in "../MyTest.asn1"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "SNMPMessage.h"

static asn_TYPE_member_t asn_MBR_SNMPMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SNMPMessage, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SNMPMessage, community),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"community"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SNMPMessage, data),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_PDUs,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"data"
		},
};
static ber_tlv_tag_t asn_DEF_SNMPMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SNMPMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version at 15 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* community at 19 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* get-request at 63 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* get-next-request at 64 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* response at 66 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* set-request at 67 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* get-bulk-request at 65 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 2, 0, 0 }, /* inform-request at 68 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 2, 0, 0 }, /* snmpV2-trap at 69 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 2, 0, 0 } /* report at 70 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SNMPMessage_specs_1 = {
	sizeof(struct SNMPMessage),
	offsetof(struct SNMPMessage, _asn_ctx),
	asn_MAP_SNMPMessage_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SNMPMessage = {
	"SNMPMessage",
	"SNMPMessage",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SNMPMessage_tags_1,
	sizeof(asn_DEF_SNMPMessage_tags_1)
		/sizeof(asn_DEF_SNMPMessage_tags_1[0]), /* 1 */
	asn_DEF_SNMPMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_SNMPMessage_tags_1)
		/sizeof(asn_DEF_SNMPMessage_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SNMPMessage_1,
	3,	/* Elements count */
	&asn_SPC_SNMPMessage_specs_1	/* Additional specs */
};

