/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyTest"
 * 	found in "../MyTest.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_MyType_H_
#define	_MyType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MyType */
typedef struct MyType {
	long	 checksum;
	long	 timeElapsed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyType;

#ifdef __cplusplus
}
#endif

#endif	/* _MyType_H_ */
