/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyTest"
 * 	found in "../MyTest.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_Message_H_
#define	_Message_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Message_PR {
	Message_PR_NOTHING,	/* No components present */
	Message_PR_intMessage,
	Message_PR_stringMessage,
	Message_PR_oidInfo
} Message_PR;

/* Message */
typedef struct Message {
	Message_PR present;
	union Message_u {
		long	 intMessage;
		OCTET_STRING_t	 stringMessage;
		OBJECT_IDENTIFIER_t	 oidInfo;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Message;

#ifdef __cplusplus
}
#endif

#endif	/* _Message_H_ */
