/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyTest"
 * 	found in "../MyTest.asn1"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "MyType.h"

static asn_TYPE_member_t asn_MBR_MyType_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MyType, checksum),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"checksum"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MyType, timeElapsed),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timeElapsed"
		},
};
static ber_tlv_tag_t asn_DEF_MyType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MyType_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* checksum at 11 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* timeElapsed at 13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MyType_specs_1 = {
	sizeof(struct MyType),
	offsetof(struct MyType, _asn_ctx),
	asn_MAP_MyType_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MyType = {
	"MyType",
	"MyType",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MyType_tags_1,
	sizeof(asn_DEF_MyType_tags_1)
		/sizeof(asn_DEF_MyType_tags_1[0]), /* 1 */
	asn_DEF_MyType_tags_1,	/* Same as above */
	sizeof(asn_DEF_MyType_tags_1)
		/sizeof(asn_DEF_MyType_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MyType_1,
	2,	/* Elements count */
	&asn_SPC_MyType_specs_1	/* Additional specs */
};

