/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyTest"
 * 	found in "../MyTest.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_BulkPDU_H_
#define	_BulkPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "VarBindList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BulkPDU */
typedef struct BulkPDU {
	long	 request_id;
	long	 non_repeaters;
	long	 max_repetitions;
	VarBindList_t	 variable_bindings;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BulkPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BulkPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _BulkPDU_H_ */
