/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyTest"
 * 	found in "../MyTest.asn1"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "PDUs.h"

static asn_TYPE_member_t asn_MBR_PDUs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.get_request),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_GetRequest_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"get-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.get_next_request),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_GetNextRequest_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"get-next-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.get_bulk_request),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_GetBulkRequest_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"get-bulk-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.response),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_Response_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"response"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.set_request),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_SetRequest_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"set-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.inform_request),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_InformRequest_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"inform-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.snmpV2_trap),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_SNMPv2_Trap_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"snmpV2-trap"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.report),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		0,
		&asn_DEF_Report_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"report"
		},
};
static asn_TYPE_tag2member_t asn_MAP_PDUs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* get-request at 63 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* get-next-request at 64 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 }, /* response at 66 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 4, 0, 0 }, /* set-request at 67 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* get-bulk-request at 65 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* inform-request at 68 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* snmpV2-trap at 69 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 } /* report at 70 */
};
static asn_CHOICE_specifics_t asn_SPC_PDUs_specs_1 = {
	sizeof(struct PDUs),
	offsetof(struct PDUs, _asn_ctx),
	offsetof(struct PDUs, present),
	sizeof(((struct PDUs *)0)->present),
	asn_MAP_PDUs_tag2el_1,
	8,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_PDUs = {
	"PDUs",
	"PDUs",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_PDUs_1,
	8,	/* Elements count */
	&asn_SPC_PDUs_specs_1	/* Additional specs */
};

