/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyTest"
 * 	found in "../MyTest.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_SimpleSyntax_H_
#define	_SimpleSyntax_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SimpleSyntax_PR {
	SimpleSyntax_PR_NOTHING,	/* No components present */
	SimpleSyntax_PR_integer_value,
	SimpleSyntax_PR_string_value,
	SimpleSyntax_PR_objectID_value
} SimpleSyntax_PR;

/* SimpleSyntax */
typedef struct SimpleSyntax {
	SimpleSyntax_PR present;
	union SimpleSyntax_u {
		long	 integer_value;
		OCTET_STRING_t	 string_value;
		OBJECT_IDENTIFIER_t	 objectID_value;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SimpleSyntax_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SimpleSyntax;

#ifdef __cplusplus
}
#endif

#endif	/* _SimpleSyntax_H_ */
