/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyTest"
 * 	found in "../MyTest.asn1"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "VarBind.h"

static asn_TYPE_member_t asn_MBR_choice_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct choice, choice.value),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ObjectSyntax,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"value"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct choice, choice.unSpecified),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unSpecified"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct choice, choice.noSuchObject),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"noSuchObject"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct choice, choice.noSuchInstance),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"noSuchInstance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct choice, choice.endOfMibView),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"endOfMibView"
		},
};
static asn_TYPE_tag2member_t asn_MAP_choice_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* integer-value at 36 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* string-value at 37 */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 1, 0, 0 }, /* unSpecified at 148 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* objectID-value at 38 */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 0, 0, 0 }, /* ipAddress-value at 41 */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 0, 0, 0 }, /* counter-value at 42 */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 0, 0, 0 }, /* unsigned-integer-value at 45 */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 0, 0, 0 }, /* timeticks-value at 43 */
    { (ASN_TAG_CLASS_APPLICATION | (4 << 2)), 0, 0, 0 }, /* arbitrary-value at 44 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* noSuchObject at 151 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, 0, 0 }, /* noSuchInstance at 152 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 4, 0, 0 } /* endOfMibView at 153 */
};
static asn_CHOICE_specifics_t asn_SPC_choice_specs_3 = {
	sizeof(struct choice),
	offsetof(struct choice, _asn_ctx),
	offsetof(struct choice, present),
	sizeof(((struct choice *)0)->present),
	asn_MAP_choice_tag2el_3,
	12,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_choice_3 = {
	"choice",
	"choice",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_choice_3,
	5,	/* Elements count */
	&asn_SPC_choice_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_VarBind_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VarBind, name),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VarBind, choice),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_choice_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"choice"
		},
};
static ber_tlv_tag_t asn_DEF_VarBind_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_VarBind_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* integer-value at 36 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* string-value at 37 */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 1, 0, 0 }, /* unSpecified at 148 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 1 }, /* name at 144 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, -1, 0 }, /* objectID-value at 38 */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 1, 0, 0 }, /* ipAddress-value at 41 */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 1, 0, 0 }, /* counter-value at 42 */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 1, 0, 0 }, /* unsigned-integer-value at 45 */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 1, 0, 0 }, /* timeticks-value at 43 */
    { (ASN_TAG_CLASS_APPLICATION | (4 << 2)), 1, 0, 0 }, /* arbitrary-value at 44 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* noSuchObject at 151 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* noSuchInstance at 152 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* endOfMibView at 153 */
};
static asn_SEQUENCE_specifics_t asn_SPC_VarBind_specs_1 = {
	sizeof(struct VarBind),
	offsetof(struct VarBind, _asn_ctx),
	asn_MAP_VarBind_tag2el_1,
	13,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_VarBind = {
	"VarBind",
	"VarBind",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_VarBind_tags_1,
	sizeof(asn_DEF_VarBind_tags_1)
		/sizeof(asn_DEF_VarBind_tags_1[0]), /* 1 */
	asn_DEF_VarBind_tags_1,	/* Same as above */
	sizeof(asn_DEF_VarBind_tags_1)
		/sizeof(asn_DEF_VarBind_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_VarBind_1,
	2,	/* Elements count */
	&asn_SPC_VarBind_specs_1	/* Additional specs */
};

